ALTER TABLE Client ADD COLUMN advertisingCampaignType CHARACTER VARYING(255);
ALTER TABLE Client ADD COLUMN advertisingCampaignNumber CHARACTER VARYING(255);
ALTER TABLE Client ADD COLUMN advertisementNumber CHARACTER VARYING(255);
ALTER TABLE Client ADD COLUMN searchQuery CHARACTER VARYING(1024);
ALTER TABLE Client ADD COLUMN searchPhrase CHARACTER VARYING(512);